/**
 * US eBay category tree helpers.
 *
 * Tree source (see PILOT.md):
 * - Mock / offline: bundled `us-category-tree.json` (vendored EBAY_US snapshot
 *   generated by `scripts/generate-ebay-us-category-tree.mjs`).
 * - Live: Commerce Taxonomy `getCategoryTree` when EBAY_CLIENT_ID/SECRET present;
 *   otherwise falls back to the bundled file.
 */

import bundled from "./us-category-tree.json";
import type {
  EbayCategoryFlatRow,
  EbayCategoryNode,
  EbayCategoryTreeMeta,
  EbayCategoryTreePayload,
} from "./types";

export type CategoryIndex = {
  byId: Map<string, EbayCategoryNode>;
  childrenOf: Map<string | null, EbayCategoryNode[]>;
  roots: EbayCategoryNode[];
  meta: EbayCategoryTreeMeta;
};

function rowsToIndex(
  payload: EbayCategoryTreePayload,
  source: EbayCategoryTreeMeta["source"],
  mode: EbayCategoryTreeMeta["mode"]
): CategoryIndex {
  const byId = new Map<string, EbayCategoryNode>();
  const childrenOf = new Map<string | null, EbayCategoryNode[]>();

  for (const row of payload.nodes as EbayCategoryFlatRow[]) {
    const [id, name, parentId, leafFlag] = row;
    const node: EbayCategoryNode = {
      categoryId: id,
      categoryName: name,
      parentId,
      leaf: leafFlag === 1,
    };
    byId.set(id, node);
    const key = parentId;
    const list = childrenOf.get(key) ?? [];
    list.push(node);
    childrenOf.set(key, list);
  }

  for (const kids of Array.from(childrenOf.values())) {
    kids.sort((a: EbayCategoryNode, b: EbayCategoryNode) =>
      a.categoryName.localeCompare(b.categoryName)
    );
  }

  const roots = childrenOf.get(null) ?? [];
  return {
    byId,
    childrenOf,
    roots,
    meta: {
      marketplaceId: payload.marketplaceId,
      categoryTreeId: payload.categoryTreeId,
      source,
      version: payload.version,
      generatedAt: payload.generatedAt,
      nodeCount: payload.nodes.length,
      mode,
    },
  };
}

let cachedBundled: CategoryIndex | null = null;

/** Load the vendored US tree (sync — safe for client + server). */
export function getBundledCategoryIndex(
  mode: EbayCategoryTreeMeta["mode"] = "mock"
): CategoryIndex {
  if (!cachedBundled || cachedBundled.meta.mode !== mode) {
    cachedBundled = rowsToIndex(
      bundled as EbayCategoryTreePayload,
      mode === "live" ? "bundled-fallback" : "bundled",
      mode
    );
  }
  return cachedBundled;
}

/** Build an index from a live Taxonomy API-shaped nested tree or flat payload. */
export function indexFromPayload(
  payload: EbayCategoryTreePayload,
  source: EbayCategoryTreeMeta["source"] = "live-api",
  mode: EbayCategoryTreeMeta["mode"] = "live"
): CategoryIndex {
  return rowsToIndex(payload, source, mode);
}

/**
 * Flatten eBay Taxonomy API nested `rootCategoryNode` into compact rows.
 */
export function flattenTaxonomyApiTree(api: {
  categoryTreeId?: string;
  categoryTreeVersion?: string;
  rootCategoryNode?: {
    category?: { categoryId?: string; categoryName?: string };
    leafCategoryTreeNode?: boolean;
    childCategoryTreeNodes?: unknown[];
  };
  applicableMarketplaceIds?: string[];
}): EbayCategoryTreePayload {
  const rows: EbayCategoryFlatRow[] = [];

  function walk(
    node: {
      category?: { categoryId?: string; categoryName?: string };
      leafCategoryTreeNode?: boolean;
      childCategoryTreeNodes?: unknown[];
    },
    parentId: string | null,
    isRoot: boolean
  ) {
    const id = node.category?.categoryId;
    const name = node.category?.categoryName;
    if (!id || !name) return;
    const kids = (node.childCategoryTreeNodes ?? []) as typeof node[];
    const leaf = kids.length === 0 || node.leafCategoryTreeNode === true;
    if (!isRoot) {
      rows.push([id, name, parentId, leaf ? 1 : 0]);
    }
    for (const child of kids) {
      walk(child, isRoot ? null : id, false);
    }
  }

  if (api.rootCategoryNode) {
    walk(api.rootCategoryNode, null, true);
  }

  return {
    marketplaceId: api.applicableMarketplaceIds?.[0] ?? "EBAY_US",
    categoryTreeId: api.categoryTreeId ?? "0",
    source: "live-api",
    version: api.categoryTreeVersion ?? new Date().toISOString(),
    generatedAt: new Date().toISOString(),
    note: "Fetched via eBay Commerce Taxonomy getCategoryTree",
    nodes: rows,
  };
}

export function getChildren(
  index: CategoryIndex,
  parentId: string | null
): EbayCategoryNode[] {
  return index.childrenOf.get(parentId) ?? [];
}

export function getNode(
  index: CategoryIndex,
  categoryId: string
): EbayCategoryNode | undefined {
  return index.byId.get(categoryId);
}

/** Breadcrumb path from root → node (names joined with " > "). */
export function getCategoryPath(
  index: CategoryIndex,
  categoryId: string
): string {
  const parts: string[] = [];
  let cur: EbayCategoryNode | undefined = index.byId.get(categoryId);
  const guard = new Set<string>();
  while (cur && !guard.has(cur.categoryId)) {
    guard.add(cur.categoryId);
    parts.unshift(cur.categoryName);
    cur = cur.parentId ? index.byId.get(cur.parentId) : undefined;
  }
  return parts.join(" > ");
}

export type CategorySearchHit = {
  categoryId: string;
  categoryName: string;
  path: string;
  leaf: boolean;
};

/** Case-insensitive name/path search (capped). */
export function searchCategories(
  index: CategoryIndex,
  query: string,
  limit = 40
): CategorySearchHit[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const hits: CategorySearchHit[] = [];
  for (const node of Array.from(index.byId.values())) {
    const path = getCategoryPath(index, node.categoryId);
    if (
      node.categoryName.toLowerCase().includes(q) ||
      path.toLowerCase().includes(q) ||
      node.categoryId.includes(q)
    ) {
      hits.push({
        categoryId: node.categoryId,
        categoryName: node.categoryName,
        path,
        leaf: node.leaf,
      });
      if (hits.length >= limit) break;
    }
  }
  hits.sort((a, b) => {
    if (a.leaf !== b.leaf) return a.leaf ? -1 : 1;
    return a.path.localeCompare(b.path);
  });
  return hits;
}

/** Ancestor ids from root to node (inclusive), for expand-to-selection. */
export function getAncestorIds(
  index: CategoryIndex,
  categoryId: string
): string[] {
  const ids: string[] = [];
  let cur: EbayCategoryNode | undefined = index.byId.get(categoryId);
  const guard = new Set<string>();
  while (cur && !guard.has(cur.categoryId)) {
    guard.add(cur.categoryId);
    ids.unshift(cur.categoryId);
    cur = cur.parentId ? index.byId.get(cur.parentId) : undefined;
  }
  return ids;
}

/** Flat options for select fallbacks / listing editor. */
export function listLeafOptions(
  index: CategoryIndex,
  limit?: number
): { id: string; path: string; leafName: string; parentId?: string }[] {
  const out: { id: string; path: string; leafName: string; parentId?: string }[] =
    [];
  for (const node of Array.from(index.byId.values())) {
    if (!node.leaf) continue;
    out.push({
      id: node.categoryId,
      path: getCategoryPath(index, node.categoryId),
      leafName: node.categoryName,
      parentId: node.parentId ?? undefined,
    });
    if (limit && out.length >= limit) break;
  }
  out.sort((a, b) => a.path.localeCompare(b.path));
  return out;
}
